# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Eduard Dohl
tagline:          'Erinnerungen'
description:      'Erinnerungen an Kindheit, Jugend, Lehr- und Wanderjahre, Junge Ehe, Familiengeschichten und Hohes Alter.'
url:              http://hyde.getpoole.com
baseurl:          https://t-karcher.github.io/eduard-dohl

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
