# Dependencies
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            Eduard Dohl
tagline:          'Erinnerungen'
description:      'Erinnerungen an Kindheit, Jugend, Lehr- und Wanderjahre, Junge Ehe und Hohes Alter.'
url:              https://t-karcher.github.io/eduard-dohl
baseurl:          /eduard-dohl

author:
  name:           'Thomas Karcher'
  url:            https://thomas-karcher.de

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/t-karcher/eduard-dohl
